name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures full history so git push/pull work correctly

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install and build dependencies
        run: |
          npm ci

      - name: Update manifest.json version from tag
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          version="${tag#v}"
          echo "Setting manifest.json version to $version"
          jq --arg ver "$version" '.version=$ver' manifest.json > tmp.$$.json && mv tmp.$$.json manifest.json
          cat manifest.json

      - name: Build plugin
        run: npm run build

      - name: Update versions.json
        run: |
          version=$(jq -r .version manifest.json)
          echo "Updating versions.json for version $version"
          if [ ! -f versions.json ]; then
            echo "{}" > versions.json
          fi
          jq --arg v "v$version" --arg ver "$version" '.[$v]=$ver' versions.json > tmp.$$.json && mv tmp.$$.json versions.json
          cat versions.json

      - name: Commit version updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json versions.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Bump version to $version"
            git pull --rebase origin main || echo "No rebase needed"
            git push origin HEAD:main
          fi

      - name: Zip plugin
        run: |
          zip -r omglol-publish.zip main.js manifest.json styles.css

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --latest \
            main.js manifest.json styles.css omglol-publish.zip
